version: '3'

services:
  odontocare_api:
    build: ./odontocare
    ports:
      - "5000:5000"

  citas_service:
    build: ./citas_service
    ports:
      - "5001:5001"
    depends_on:
      - odontocare_api
    environment:
      - MAIN_API_URL=http://odontocare_api:5000
